#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0' #Step 0
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker' #Step 1
  args: ['tag', 'workspace_app:latest', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
