#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'eu.gcr.io/opencti/cti-image']
images: ['eu.gcr.io/opencti/cti-image']
