#cloudbuild.yaml
steps:
- name: 'docker/compose:1.19.0' #Step 0
  args: ['up', '-d']
- name: 'docker/compose:1.19.0' #Step 1
  args: ['-f', 'docker-compose.yml','build']
images: ['eu.gcr.io/opencti/cti-image']
